### ISSUE TITLE
(Mcw Windows 1.18.2) Mod Loading has failed with every compat mod

### ISSUE THREAD

**Issue by 5stigma** [sketchmacaw/MacawsModsIssues#243]
Mcw Windows Mod Loading has failed with every compat mod

[crash-2022-11-24_20.43.02-fml.txt](https://github.com/sketchmacaw/MacawsModsIssues/files/10088208/crash-2022-11-24_20.43.02-fml.txt)

**Comment by sketchmacaw** [comment]
Should be fixed in the latest every compat update

**Comment by superdude808** [comment]
while this issue is closed it mus be pointed out that it looks like the every compat dev team is no longer updating their 1.18.2 version so the latest update to Mcw Windows will remain incompatible unless it is patched on Mcw Windows side of things
whilest i might be wrong about this it must be noted that the every compat dev team only pushed a fix for this crash to their 1.19.2 version and have not updated their 1.18.2 version since the end of October
