### ISSUE TITLE
Modrinth

### ISSUE THREAD

**Issue by ColonelGerdauf** [sketchmacaw/MacawsModsIssues#301]
I wonder if it is worthwhile to have the Macaw mods also uploaded to Modrinth. It will be a lot easier for everyone, especially in the context of external launchers, and it will be useful in the scope of the modpacks that are usually Fabric.

With that being said, I can understand if it adds too much extra busywork.

**Comment by sketchmacaw** [comment]
It is planned

**Comment by Faeranne** [comment]
Really happy to hear this as our work-in-progress pack is gonna be on modrinth soon, and including things like Bridges and Roofs would be awesome.  Knowing this will take a while (setting up tooling and what not can take time), does the existing permission included in the FAQ under most of your mods cover including the mod in a Modrinth pack right now, since that would require uploading it as an override?

**Comment by AlexanderwithaA** [comment]
Awesome to see this is happening, would fit great into a skyblock!

**Comment by Konclan** [comment]
Still waiting for Bridges, Fences and Walls, and Roofs to make it over to Modrinth.

**Comment by sketchmacaw** [comment]
They are all coming this month, don't worry.

**Comment by sketchmacaw** [comment]
Done, all of the Macaw's mods are on Modrinth too

**Comment by ColonelGerdauf** [comment]
Nice! I would suggest that, just for the sake of parity, to include 1.12 builds.

As a whole, this is a task accomplished.
